version: "3"

services:
  postgres:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: java
      POSTGRES_PASSWORD: example
      POSTGRES_DB: java
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/java
      SPRING_DATASOURCE_USERNAME: java
      SPRING_DATASOURCE_PASSWORD: example
      FLYWAY_USER: java
      FLYWAY_PASSWORD: example
      SERVER_PORT: 80
    ports:
      - 8084:80
    depends_on:
      - postgres

volumes:
  postgres_data:
