version: "3"

services:
  mysql:
    restart: unless-stopped
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: java
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: java
    #ports: 
    #  - 3306:3306
    volumes: 
      - mysql_data:/var/lib/mysql

  app:
    restart: unless-stopped
    image: docker.pkg.github.com/wlp2s0/basic-java-web-services/java-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/java
      SPRING_DATASOURCE_USERNAME: java
      SPRING_DATASOURCE_PASSWORD: example
      # Hikari (try to fix 500 errors when nuked, timeouts are in ms)
      # spring.datasource.hikari.leakDetectionThreshold=300000
      # SPRING_DATASOURCE_HIKARI_LEAKDETECTIONTHRESHOLD: 3000000
      # spring.datasource.hikari.connectionTimeout
      # SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: 3000000
      # spring.datasource.hikari.idleTimeout
      # SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: 120000
      # FLYWAY_USER: java
      # FLYWAY_PASSWORD: example
      SERVER_PORT: 80
    ports:
      - 8084:80
    depends_on:
      - mysql

volumes:
  mysql_data:
