version: "3"

services:
  postgres:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: java
      POSTGRES_PASSWORD: example
      POSTGRES_DB: java
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    restart: unless-stopped
    image: docker.pkg.github.com/wlp2s0/basic-java-web-services/java-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/java
      SPRING_DATASOURCE_USERNAME: java
      SPRING_DATASOURCE_PASSWORD: example
      # Hikari (try to fix 500 errors when nuked, timeouts are in ms)
      # spring.datasource.hikari.leakDetectionThreshold=300000
      # SPRING_DATASOURCE_HIKARI_LEAKDETECTIONTHRESHOLD: 3000000
      # spring.datasource.hikari.connectionTimeout
      # SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: 3000000
      # spring.datasource.hikari.idleTimeout
      # SPRING_DATASOURCE_HIKARI_IDLETIMEOUT: 120000
      # FLYWAY_USER: java
      # FLYWAY_PASSWORD: example
      SERVER_PORT: 80
    ports:
      - 8084:80
    depends_on:
      - postgres

volumes:
  postgres_data:
